export const PortfolioImages = [
  "/Portfolio/Portfolio_1.jpg",
  "/Portfolio/Portfolio_2.jpg",
  "/Portfolio/Portfolio_3.jpg",
  "/Portfolio/Portfolio_4.jpg",
  "/Portfolio/Portfolio_5.jpg",
  "/Portfolio/Portfolio_6.jpg",
  "/Portfolio/Portfolio_7.jpg",
  "/Portfolio/Portfolio_8.jpg",
  "/Portfolio/Portfolio_9.jpg",
  "/Portfolio/Portfolio_10.jpg",
  "/Portfolio/Portfolio_11.png",
  "/Portfolio/Portfolio_12.png",
  "/Portfolio/Portfolio_13.png",
  "/Portfolio/Portfolio_14.jpg",
];
